services:

  postgres:
    restart: unless-stopped
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

  nestapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    env_file: .env
    ports:
      - '3000:3000'

volumes:
  postgres-data:
